#include <sstream>
#include <fstream>
#include <iostream>
#include <string.h>

#include <vector>
#include <unordered_map>

int main(int argc, char** argv)
{
    std::ifstream sample(argc > 1 ? argv[1]: "../assets/car.stl");

    printf("#pragma once\n\n");
    printf("//AUTOGENERATED FILE WARNING!!!!!\n\n");
    printf("#ifdef __AVR__\n#include <avr/pgmspace.h>\n#endif\n\n");
    printf("const uint16_t PROGMEM obj[] =\n{\n");

    int32_t ndx = 0;
    std::vector<float> verts;
    std::unordered_map<float, uint8_t> values;

    std::string line;
    while(std::getline(sample, line))
    {
        std::istringstream iss(line);
        if(line.find("vertex") != std::string::npos)
        {
            char stlSyntax[32];
            strcpy(stlSyntax, line.c_str());

            char* token = strtok(stlSyntax," ");
            token = strtok (nullptr, " "); //Remove word vertex
            while(token != nullptr)
            {
                auto result = values.insert(std::pair<float, uint8_t>(atof(token), ndx));
                verts.push_back(result.first->second);
                if(result.second) ndx++;
                token = strtok(nullptr, " ");

                result = values.insert(std::pair<float, uint8_t>(atof(token), ndx));
                verts.push_back(result.first->second);
                if(result.second) ndx++;
                token = strtok(nullptr, " ");

                result = values.insert(std::pair<float, uint8_t>(atof(token), ndx));
                verts.push_back(result.first->second);
                if(result.second) ndx++;
                token = strtok(nullptr, " ");
            }
        }
    }

    printf("    %d,\n", (uint16_t)verts.size()/3);
    for(std::vector<float>::iterator iter = verts.begin(); iter != verts.end();)
    {
        printf("    %.0f,", *iter++);
        printf("    %.0f,", *iter++);
        printf("    %.0f,\n", *iter++);
    }

    printf("};");

    ndx = 0;
    printf("\n\nconst float PROGMEM ndxToValue[] =\n{ ");
    std::unordered_map<float,uint8_t>::iterator iter = values.begin();
    while(values.size() > 0)
    {
        while(iter->second != ndx)
        {
            iter++;
        }

        printf("%.2f, ", iter->first);
        values.erase(iter);
        iter = values.begin();
        ndx++;
    }

    printf("};\n");
}
