#include <sstream>
#include <fstream>
#include <iostream>
#include <string.h>

int main(int argc, char** argv)
{
    std::ifstream sample(argc > 1 ? argv[1]: "../assets/car.stl");

    printf("#pragma once\n\n");
    printf("//AUTOGENERATED FILE WARNING!!!!!\n\n");
    printf("#ifdef __AVR__\n#include <avr/pgmspace.h>\n#endif\n\n");
    printf("const float PROGMEM obj[] =\n{\n");

    std::string line;
    while(std::getline(sample, line))
    {
        std::istringstream iss(line);
        if(line.find("vertex") != std::string::npos)
        {
            char stlSyntax[32];
            strcpy(stlSyntax, line.c_str());

            char* token = strtok(stlSyntax," ");
            token = strtok (nullptr, " "); //Remove word vertex
            while(token != nullptr)
            {
                printf("    %.2f,", atof(token));
                token = strtok(nullptr, " ");
                printf("    %.2f,", atof(token));
                token = strtok(nullptr, " ");
                printf("    %.2f,\n", atof(token));
                token = strtok(nullptr, " ");
            }
        }
    }

    printf("};");
}
