#include <sstream>
#include <fstream>
#include <iostream>
#include <string.h>

#include <vector>

int main(int argc, char** argv)
{
    std::ifstream sample(argc > 1 ? argv[1]: "../assets/car.stl");

    printf("#pragma once\n\n");
    printf("//AUTOGENERATED FILE WARNING!!!!!\n\n");
    printf("#ifdef __AVR__\n#include <avr/pgmspace.h>\n#endif\n\n");
    printf("const float PROGMEM obj[] =\n{\n");

    std::vector<float> verts;

    std::string line;
    while(std::getline(sample, line))
    {
        std::istringstream iss(line);
        if(line.find("vertex") != std::string::npos)
        {
            char stlSyntax[32];
            strcpy(stlSyntax, line.c_str());

            char* token = strtok(stlSyntax," ");
            token = strtok (nullptr, " "); //Remove word vertex
            while(token != nullptr)
            {
                verts.push_back(atof(token));
                token = strtok(nullptr, " ");
                verts.push_back(atof(token));
                token = strtok(nullptr, " ");
                verts.push_back(atof(token));
                token = strtok(nullptr, " ");
            }
        }
    }

    printf("    %.2f,\n", (float)verts.size()/3);
    for(std::vector<float>::iterator iter = verts.begin(); iter != verts.end();)
    {
        printf("    %.2f,", *iter++);
        printf("    %.2f,", *iter++);
        printf("    %.2f,\n", *iter++);
    }

    printf("};");
}
